[package]
name = "advent2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "advent2024"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.0"
tempfile = "3.14.0"
